package conn.common;
/**
 * 消息类型
 * @author 戴思琪
 *
 */
public interface MessageType {
	
	//CLIENT	
	String C_REQ_VERIFYUSER 		= "C_REQ_VERIFYUSER"; 		// 登录	
	String C_REQ_UPDATE 			= "C_REQ_UPDATE";			//更新数据
	String C_REQ_SELECT_USERS 		= "C_REQ_SELECT_USERS";
	String C_REQ_SELECT_STUDENTS	= "C_REQ_SELECT_STUDENTS";
	String C_REQ_SELECT_TEACHERS 	= "C_REQ_SELECT_TEACHERS";
	String C_REQ_INSERT 			= "C_REQ_INSERT";
	String C_REQ_DELETE 			= "C_REQ_DELETE";
	String C_REQ_SELECT_GOODS       = "C_REQ_SELECT_GOODS";
	//Library
	String C_REQ_SELECT_BOOKS 				= "C_REQ_SELECT_BOOKS";
	String C_REQ_UPDATE_BOOK 				= "C_REQ_UPDATE_BOOK";
	String C_REQ_ADD_BOOK 					= "C_REQ_ADD_BOOK";
	String C_REQ_SELECT_AUTHORITY 			= "C_REQ_SELECT_AUTHORITY";
	String C_REQ_UPDATE_AUTHORITY 			= "C_REQ_UPDATE_AUTHORITY";
	String C_REQ_SELECT_NONRETURNED_BOOK 	= "C_REQ_SELECT_NONRETURNED_BOOK";
	String C_REQ_SELECT_ALL_BORROWINFO_BOOK = "C_REQ_SELECT_ALL_BORROWINFO_BOOK";
	String C_REQ_RETURN_BOOK 				= "C_REQ_RETURN_BOOK";
	String C_REQ_BORROW_BOOK 				= "C_REQ_BORROW_BOOK";
	String C_REQ_SELECT_NONRETURNED_USER 	= "C_REQ_SELECT_NONRETURNED_USER";
	String C_REQ_SELECT_ALL_BORROWINFO_USER = "C_REQ_SELECT_ALL_BORROWINFO_USER";
	//end library







	
}

